leftnav:
- identifier: cfe41ae2-b28b-52bf-3892-b74656a883c2
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 91771e35-7a01-0447-cccb-5d0ad62592bb
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: a2424c14-f8f8-4dfa-0289-77468d3d08f4
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 30
- identifier: 5f8e7d4e-7d72-5233-7ddb-6fc69f21574a
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: 6b996310-6764-4ce2-6271-5488b7953729
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
